---
# tasks file for apache-configure
- name: Install dependencies
  package:
    name: ['openssl', 'httpd', 'mod_ssl']
    state: present

- name: Insert Index Page
  template:
    src: index.html
    dest: /var/www/html/index.html

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Pennsylvania/L=Philadelphia/O=BrianPayne/CN=brianpayne-apachedemo" -days 3650 -keyout /etc/pki/tls/private/localhost.key -out /etc/pki/tls/certs/localhost.crt -extensions v3_ca creates=/etc/pki/tls/certs/localhost.crt
  notify: restart apache service

- name: Insert httpd.conf
  template:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf
  notify:
    restart apache service

- name: Start httpd
  service:
    name: httpd
    state: started
    enabled: true
