---
- name: Install and configure Apache
  hosts: 3.88.27.66
  remote_user: ec2-user
  become: yes
  become_method: sudo

  tasks:
  - name: Install openssh
    yum:
      name: openssh
      state: present

  - name: Install apache
    yum:
      name: httpd
      state: present

  - name: Install mod24_ssl
    yum:
      name:  mod_ssl
      state: present

  - name: Insert Index Page
    template:
      src: index.html
      dest: /var/www/html/index.html

  - name: Insert public key
    copy:
      src: "public.crt"
      dest: "/etc/pki/tls/certs/localhost.crt"
      owner: root
      group: root
      mode: 0644

  - name: Insert private key
    copy:
      src: "private.key"
      dest: "/etc/pki/tls/private/localhost.key"
      owner: root
      group: root
      mode: 0400

  - name: Start httpd
    service:
      name: httpd
      state: reloaded
